<?php

namespace HexTechnology\Leaves\Assets\Manufacturers;


use HexTechnology\Models\Manufacturer;
use Rhubarb\Leaf\Crud\Leaves\CrudView;

class ManufacturersCollectionView extends CrudView
{
    protected function printViewContent()
    {
        parent::printViewContent(); // TODO: Change the autogenerated stub
        print "<a href='add/'>Add</a>";
        print "<ul>";
        $manufacturers = Manufacturer::all();
        if (sizeof($manufacturers)>0)
            foreach ( $manufacturers as $manufacturer )
                print'<li><a href="'.$manufacturer->ManufacturerID.'/">'.$manufacturer->ManufacturerName.'</li>';
        print "</ul>";
    }

}