<?php

namespace HexTechnology\Leaves\Assets;

use HexTechnology\Models\SerialNumber;
use Rhubarb\Crown\Exceptions\ForceResponseException;
use Rhubarb\Crown\Response\HtmlResponse;
use Rhubarb\Crown\Response\RedirectResponse;
use Rhubarb\Leaf\Crud\Leaves\CrudLeaf;

class AssetsItem extends CrudLeaf
{

    /**
     * @var AssetsItemModel
     */
    protected $model;

    /**
     * Returns the name of the standard view used for this leaf.
     *
     * @return string
     */
    protected function getViewClass()
    {
        return AssetsItemView::class;
    }

    protected function createModel()
    {
        return new AssetsItemModel();
    }

    protected function onModelCreated()
    {

        $this->model->serialAddedEvent->attachHandler(function () {
            if ($this->model->SerialNumberCode != "") {
                $serial = new SerialNumber();
                $serial->AssetID = $this->model->restModel->UniqueIdentifier;
                $serial->SerialNumberCode = $this->model->SerialNumberCode;
                $serial->CurrentValue = $this->model->SerialNumberCurrentValue;
                $serial->InitialValue = $this->model->SerialNumberCurrentValue;
                $serial->PurchaseDate = $this->model->SerialNumberPurchaseDate;
                $serial->save();

                //Clear the fields by forcing a refresh, also conveniently adds that serial number to the table
//                $this->model->SerialNumberCode = "";
//                $this->model->SerialNumberInitialPrice = "";
//                $this->model->SerialNumberCurrentValue = "";
//                $this->model->SerialNumberPurchaseDate = "";

				throw new ForceResponseException(new RedirectResponse("."));
            }
        });

        $this->model->testEvent->attachHandler(function($magicParameter){
        	$magicParameter .= " Monkeys Jump";
			return "A random string " . $magicParameter;
		});

//        $this->model->SerialNumberCode = "";
//        $this->model->SerialNumberInitialPrice = "";
//        $this->model->SerialNumberCurrentValue = "";
//        $this->model->SerialNumberPurchaseDate = "";

            parent::onModelCreated(); // TODO: Change the autogenerated stub
    }

}