<?php

namespace HexTechnology\Layouts;

use Rhubarb\Leaf\Crud\Leaves\CrudView;

class zHexTechnologyItemView extends CrudView
{
    /**
     * Set this to false in your subclass to prevent the button bar being printed in the usual place.
     * @see printButtonBar()
     * @var bool
     */
    protected $shouldPrintButtonBar = true;

    protected function createSubLeaves()
    {
        parent::createSubLeaves(); // TODO: Change the autogenerated stub

        $this->leaves["Save"]->addCssClassNames("btn btn-success");
        $this->leaves["Cancel"]->addCssClassNames("btn btn-warning");
        $this->leaves["Delete"]->addCssClassNames("btn btn-danger");
    }

    /**
     * This is final so that no subclasses can override it
     */
    final function printViewContent()
    {
        parent::printViewContent();
        ?>
        <h1 class='title'><?= $this->getTitle() ?></h1>
        <div class='item'>
            <!--     Back Button       -->
            <span class='btn btn-warning'>
                <img src='/static/images/back.svg' height='13px' style='margin-right:5px; margin-bottom:-1px;'>
                <a href='../'>
                    <?php
                    print $this->model->restModel->getModelName() . "s";
                    ?>
                </a>
            </span>
            <!--    End of Back Button    -->
        <?php
        $this->printInnerContent();

        // Handling of $shouldPrintButtonBar
        ($this->shouldPrintButtonBar)? $this->printButtonBar() : "";

        $this->printBelowButtonBar();
    }

    /**
     * Override this to put stuff into the page below the back button
     */
    protected function printInnerContent()
    {
    }

    protected function printBelowButtonBar()
    {
    }

    /**
     * If $shouldPrintButtonBar is false, you can print this wherever you want in your subclass's print inner content
     * If you copy
     */
    protected function printButtonBar()
    {
        print "<div class='button-bar'>";
        print $this->leaves["Save"];
        print $this->leaves["Cancel"];
        print $this->leaves["Delete"];
        print "</div>";
    }

}